.TH "oggz-codecs" "1" 
.SH "NAME" 
oggz-info \(em Display a list of codecs found in one or more Ogg files and their bitstreams. 
 
.SH "SYNOPSIS" 
.PP 
\fBoggz-codecs\fR [\-a  | \-\-all ]  [\-m  | \-\-mime ]  filename \&...  
.PP 
\fBoggz-codecs\fR [\-h  | \-\-help ]  [\-v  | \-\-version ]  
.SH "Description" 
.PP 
\fBoggz-codecs\fR displays a list of codecs found in one or more 
Ogg files and their bitstreams. 
 
.SH "Options" 
.PP 
\fBoggz-codecs\fR accepts the following options: 
 
.SS "Display options" 
.IP "\-a, \-\-all" 10 
Display an entry for every bitstream, rather than displaying each codec once, even if present more than once. 
.IP "\-m, \-\-mime" 10 
Display each codec's MIME type, instead of its name. 
.SS "Miscellaneous options" 
.IP "\-h, \-\-help" 10 
Display usage information and exit. 
.IP "\-v, \-\-version" 10 
Output version information and exit. 
.SH "AUTHOR" 
.PP 
Conrad Parker        March 10, 2005;      
.SH "COPYRIGHT" 
.PP 
Copyright \(co 2005 CSIRO Australia 
 
.SH "SEE ALSO" 
.PP 
\fBoggzinfo\fP\fB(1)\fP       \fBhogg\fP\fB(1)\fP      
.\" created by instant / docbook-to-man, Mon 23 Feb 2009, 12:35 
